version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nxt-newday-backend:latest
    ports:
      - "4000"
    environment:
      - DATABASE_URL=${{project.DATABASE_URL}}
      - JWT_SECRET=${{project.JWT_SECRET}}
      - ENCRYPTION_KEY=${{project.ENCRYPTION_KEY}}
      - REDIS_URL=${{project.REDIS_URL}}
      - API_BASE_URL=${{project.API_BASE_URL}}
      - FRONTEND_URL=${{project.FRONTEND_URL}}
      - LOG_LEVEL=${{project.LOG_LEVEL}}
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dokploy-network:
    external: true