version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile # or Dockerfile.production
    container_name: nxt-api
    env_file: .backend.env
    ports:
      - '4000:4000'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:4000/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
