version: '3.8'

services:
  nxt-backend:
    build: .
    container_name: nxt-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .backend.env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/dashboard/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./uploads:/app/uploads
